services:
  ambev.developerevaluation.database:
    container_name: ambev_developer_evaluation_database
    image: postgres:13
    environment:
      POSTGRES_DB: developer_evaluation
      POSTGRES_USER: developer
      POSTGRES_PASSWORD: ev@luAt10n
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U developer -d developer_evaluation"]
      interval: 5s
      timeout: 5s
      retries: 5

  pgadmin:
    container_name: pgadmin4
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: aurilio@teste.com
      PGADMIN_DEFAULT_PASSWORD: aurilio@1
    ports:
      - "8085:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    depends_on:
      - ambev.developerevaluation.database
    restart: unless-stopped

volumes:
  db-data:
  pgadmin-data:
